# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(name: "Ben Morgan-Cleveland", username: "Ben1", email: "email", img_url: "https://images-na.ssl-images-amazon.com/images/S/sgp-catalog-images/region_US/turner-ben_S1-Full-Image_GalleryBackground-en-US-1600781973929._SX1080_.jpg")
Guide.create(user_id: 1, title: "Cooking Shrimp", category: "Cooking", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac odio tempor orci dapibus ultrices in. Laoreet non curabitur gravida arcu ac tortor. Tortor id aliquet lectus proin nibh nisl condimentum id. Lobortis feugiat vivamus at augue eget. Pellentesque diam volutpat commodo sed. Morbi blandit cursus risus at. Molestie nunc non blandit massa enim. Magnis dis parturient montes nascetur ridiculus mus mauris. Viverra nibh cras pulvinar mattis nunc sed blandit. Sit amet commodo nulla facilisi nullam vehicula ipsum. Maecenas pharetra convallis posuere morbi leo urna molestie at. Et ligula ullamcorper malesuada proin libero nunc consequat. Semper auctor neque vitae tempus quam pellentesque nec. Sed felis eget velit aliquet sagittis id consectetur purus ut. Elit ullamcorper dignissim cras tincidunt. Semper eget duis at tellus at urna condimentum. Lectus nulla at volutpat diam ut.

    Ultrices dui sapien eget mi proin sed libero enim sed. Risus viverra adipiscing at in tellus integer feugiat. Facilisis sed odio morbi quis commodo odio aenean. Amet risus nullam eget felis eget nunc. Ut porttitor leo a diam sollicitudin tempor id eu. Lectus sit amet est placerat in egestas erat. Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Nisl rhoncus mattis rhoncus urna neque viverra. Sit amet porttitor eget dolor morbi non arcu risus. At in tellus integer feugiat scelerisque varius morbi enim nunc. Tincidunt lobortis feugiat vivamus at augue eget. Vivamus at augue eget arcu dictum varius duis. Maecenas pharetra convallis posuere morbi leo urna molestie. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Tortor id aliquet lectus proin nibh nisl condimentum id. Id aliquet risus feugiat in ante metus dictum at. Bibendum at varius vel pharetra vel turpis nunc eget. Justo laoreet sit amet cursus sit amet dictum sit. Enim ut tellus elementum sagittis vitae et leo duis ut. Rutrum tellus pellentesque eu tincidunt tortor.
    
    Eu consequat ac felis donec. Id nibh tortor id aliquet lectus. Cum sociis natoque penatibus et magnis dis parturient montes. Vulputate dignissim suspendisse in est ante in. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Volutpat est velit egestas dui id ornare arcu odio. Ullamcorper sit amet risus nullam eget felis eget nunc lobortis. Congue quisque egestas diam in arcu cursus euismod quis viverra. Enim ut tellus elementum sagittis vitae et. In hac habitasse platea dictumst quisque. Morbi tincidunt ornare massa eget. Nunc faucibus a pellentesque sit amet porttitor eget.", img_url: "https://cimg3.ibsrv.net/cimg/www.fitday.com/693x350_85-1/331/shrimpyshrimp-256331.jpg" )

User.create(name: "Ori Markowitz", username: "Ori1", email: "email", img_url: "https://cimg3.ibsrv.net/cimg/www.fitday.com/693x350_85-1/331/shrimpyshrimp-256331.jpg")
Guide.create(user_id: 2, title: "Cooking Lobster", category: "Cooking", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac odio tempor orci dapibus ultrices in. Laoreet non curabitur gravida arcu ac tortor. Tortor id aliquet lectus proin nibh nisl condimentum id. Lobortis feugiat vivamus at augue eget. Pellentesque diam volutpat commodo sed. Morbi blandit cursus risus at. Molestie nunc non blandit massa enim. Magnis dis parturient montes nascetur ridiculus mus mauris. Viverra nibh cras pulvinar mattis nunc sed blandit. Sit amet commodo nulla facilisi nullam vehicula ipsum. Maecenas pharetra convallis posuere morbi leo urna molestie at. Et ligula ullamcorper malesuada proin libero nunc consequat. Semper auctor neque vitae tempus quam pellentesque nec. Sed felis eget velit aliquet sagittis id consectetur purus ut. Elit ullamcorper dignissim cras tincidunt. Semper eget duis at tellus at urna condimentum. Lectus nulla at volutpat diam ut.

    Ultrices dui sapien eget mi proin sed libero enim sed. Risus viverra adipiscing at in tellus integer feugiat. Facilisis sed odio morbi quis commodo odio aenean. Amet risus nullam eget felis eget nunc. Ut porttitor leo a diam sollicitudin tempor id eu. Lectus sit amet est placerat in egestas erat. Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Nisl rhoncus mattis rhoncus urna neque viverra. Sit amet porttitor eget dolor morbi non arcu risus. At in tellus integer feugiat scelerisque varius morbi enim nunc. Tincidunt lobortis feugiat vivamus at augue eget. Vivamus at augue eget arcu dictum varius duis. Maecenas pharetra convallis posuere morbi leo urna molestie. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Tortor id aliquet lectus proin nibh nisl condimentum id. Id aliquet risus feugiat in ante metus dictum at. Bibendum at varius vel pharetra vel turpis nunc eget. Justo laoreet sit amet cursus sit amet dictum sit. Enim ut tellus elementum sagittis vitae et leo duis ut. Rutrum tellus pellentesque eu tincidunt tortor.
    
    Eu consequat ac felis donec. Id nibh tortor id aliquet lectus. Cum sociis natoque penatibus et magnis dis parturient montes. Vulputate dignissim suspendisse in est ante in. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Volutpat est velit egestas dui id ornare arcu odio. Ullamcorper sit amet risus nullam eget felis eget nunc lobortis. Congue quisque egestas diam in arcu cursus euismod quis viverra. Enim ut tellus elementum sagittis vitae et. In hac habitasse platea dictumst quisque. Morbi tincidunt ornare massa eget. Nunc faucibus a pellentesque sit amet porttitor eget.", img_url: "https://www.earthfoodandfire.com/wp-content/uploads/2018/06/A-complete-guide-to-cooking-atlantic-lobster.jpg" )


User.create(name: "Aaron Judge", username: "Judge99", email: "email", img_url: "https://a.espncdn.com/i/headshots/mlb/players/full/33192.png")
Guide.create(user_id: 3, title: "Hitting Homeruns", category: "Sports", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac odio tempor orci dapibus ultrices in. Laoreet non curabitur gravida arcu ac tortor. Tortor id aliquet lectus proin nibh nisl condimentum id. Lobortis feugiat vivamus at augue eget. Pellentesque diam volutpat commodo sed. Morbi blandit cursus risus at. Molestie nunc non blandit massa enim. Magnis dis parturient montes nascetur ridiculus mus mauris. Viverra nibh cras pulvinar mattis nunc sed blandit. Sit amet commodo nulla facilisi nullam vehicula ipsum. Maecenas pharetra convallis posuere morbi leo urna molestie at. Et ligula ullamcorper malesuada proin libero nunc consequat. Semper auctor neque vitae tempus quam pellentesque nec. Sed felis eget velit aliquet sagittis id consectetur purus ut. Elit ullamcorper dignissim cras tincidunt. Semper eget duis at tellus at urna condimentum. Lectus nulla at volutpat diam ut.

    Ultrices dui sapien eget mi proin sed libero enim sed. Risus viverra adipiscing at in tellus integer feugiat. Facilisis sed odio morbi quis commodo odio aenean. Amet risus nullam eget felis eget nunc. Ut porttitor leo a diam sollicitudin tempor id eu. Lectus sit amet est placerat in egestas erat. Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Nisl rhoncus mattis rhoncus urna neque viverra. Sit amet porttitor eget dolor morbi non arcu risus. At in tellus integer feugiat scelerisque varius morbi enim nunc. Tincidunt lobortis feugiat vivamus at augue eget. Vivamus at augue eget arcu dictum varius duis. Maecenas pharetra convallis posuere morbi leo urna molestie. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Tortor id aliquet lectus proin nibh nisl condimentum id. Id aliquet risus feugiat in ante metus dictum at. Bibendum at varius vel pharetra vel turpis nunc eget. Justo laoreet sit amet cursus sit amet dictum sit. Enim ut tellus elementum sagittis vitae et leo duis ut. Rutrum tellus pellentesque eu tincidunt tortor.
    
    Eu consequat ac felis donec. Id nibh tortor id aliquet lectus. Cum sociis natoque penatibus et magnis dis parturient montes. Vulputate dignissim suspendisse in est ante in. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Volutpat est velit egestas dui id ornare arcu odio. Ullamcorper sit amet risus nullam eget felis eget nunc lobortis. Congue quisque egestas diam in arcu cursus euismod quis viverra. Enim ut tellus elementum sagittis vitae et. In hac habitasse platea dictumst quisque. Morbi tincidunt ornare massa eget. Nunc faucibus a pellentesque sit amet porttitor eget.", img_url: "https://lh3.googleusercontent.com/proxy/62MyDJV9yy9xIFgylhE7uqGhjO5jPLxyJbbc1x_HiXag7uIsKKj-zpK4Oc04xGsEJPUIfmdi-JrN0YUBUCiU1nD-vgwcdYznWe79wIxyDVGR5mI")

User.create(name: "Andy Warholia", username: "factoryManager1", email: "email@gmail.com", img_url: "https://www.artnews.com/wp-content/uploads/2020/04/Andy-in-Studio%E2%80%94New-York-Union-Square-1976-Photograph-by-Michael-Childers.jpg?w=635")
Guide.create(user_id: 4, title: "Art Galleries to Check Out in the LES", category: "Fine Arts & Leisure", content: "James Fuentes Gallery, Mitchell Algus, Artists Space, Kai Matsumiya, Bureau. They are free and open to public.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac odio tempor orci dapibus ultrices in. Laoreet non curabitur gravida arcu ac tortor. Tortor id aliquet lectus proin nibh nisl condimentum id. Lobortis feugiat vivamus at augue eget. Pellentesque diam volutpat commodo sed. Morbi blandit cursus risus at. Molestie nunc non blandit massa enim. Magnis dis parturient montes nascetur ridiculus mus mauris. Viverra nibh cras pulvinar mattis nunc sed blandit. Sit amet commodo nulla facilisi nullam vehicula ipsum. Maecenas pharetra convallis posuere morbi leo urna molestie at. Et ligula ullamcorper malesuada proin libero nunc consequat. Semper auctor neque vitae tempus quam pellentesque nec. Sed felis eget velit aliquet sagittis id consectetur purus ut. Elit ullamcorper dignissim cras tincidunt. Semper eget duis at tellus at urna condimentum. Lectus nulla at volutpat diam ut.

    Ultrices dui sapien eget mi proin sed libero enim sed. Risus viverra adipiscing at in tellus integer feugiat. Facilisis sed odio morbi quis commodo odio aenean. Amet risus nullam eget felis eget nunc. Ut porttitor leo a diam sollicitudin tempor id eu. Lectus sit amet est placerat in egestas erat. Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Nisl rhoncus mattis rhoncus urna neque viverra. Sit amet porttitor eget dolor morbi non arcu risus. At in tellus integer feugiat scelerisque varius morbi enim nunc. Tincidunt lobortis feugiat vivamus at augue eget. Vivamus at augue eget arcu dictum varius duis. Maecenas pharetra convallis posuere morbi leo urna molestie. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Tortor id aliquet lectus proin nibh nisl condimentum id. Id aliquet risus feugiat in ante metus dictum at. Bibendum at varius vel pharetra vel turpis nunc eget. Justo laoreet sit amet cursus sit amet dictum sit. Enim ut tellus elementum sagittis vitae et leo duis ut. Rutrum tellus pellentesque eu tincidunt tortor.
    
    Eu consequat ac felis donec. Id nibh tortor id aliquet lectus. Cum sociis natoque penatibus et magnis dis parturient montes.", img_url: "https://www.walksofnewyork.com/blog/wp-content/uploads/2015/07/Lower-East-Side-galleries.jpg" )

User.create(name: "Billy Name", username: "factoryPhotographer1", email: "bemail@gmail.com", img_url: "https://upload.wikimedia.org/wikipedia/commons/5/55/Billy_Name_%28Greenman%29_by_David_Shankbone.jpg")
Guide.create(user_id: 5, title: "Art Galleries to Check Out in the UES", category: "Fine Arts & Leisure", content: "Buchholz Galerie, They are free and open to public.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac odio tempor orci dapibus ultrices in. Laoreet non curabitur gravida arcu ac tortor. Tortor id aliquet lectus proin nibh nisl condimentum id. Lobortis feugiat vivamus at augue eget. Pellentesque diam volutpat commodo sed. Morbi blandit cursus risus at. Molestie nunc non blandit massa enim. Magnis dis parturient montes nascetur ridiculus mus mauris. Viverra nibh cras pulvinar mattis nunc sed blandit. Sit amet commodo nulla facilisi nullam vehicula ipsum. Maecenas pharetra convallis posuere morbi leo urna molestie at. Et ligula ullamcorper malesuada proin libero nunc consequat. Semper auctor neque vitae tempus quam pellentesque nec. Sed felis eget velit aliquet sagittis id consectetur purus ut. Elit ullamcorper dignissim cras tincidunt. Semper eget duis at tellus at urna condimentum. Lectus nulla at volutpat diam ut.
    Ultrices dui sapien eget mi proin sed libero enim sed. Risus viverra adipiscing at in tellus integer feugiat. Facilisis sed odio morbi quis commodo odio aenean. Amet risus nullam eget felis eget nunc. Ut porttitor leo a diam sollicitudin tempor id eu. Lectus sit amet est placerat in egestas erat. Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Nisl rhoncus mattis rhoncus urna neque viverra. Sit amet porttitor eget dolor morbi non arcu risus. At in tellus integer feugiat scelerisque varius morbi enim nunc. Tincidunt lobortis feugiat vivamus at augue eget. Vivamus at augue eget arcu dictum varius duis. Maecenas pharetra convallis posuere morbi leo urna molestie. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Tortor id aliquet lectus proin nibh nisl condimentum id. Id aliquet risus feugiat in ante metus dictum at. Bibendum at varius vel pharetra vel turpis nunc eget. Justo laoreet sit amet cursus sit amet dictum sit. Enim ut tellus elementum sagittis vitae et leo duis ut. Rutrum tellus pellentesque eu tincidunt tortor.
    Eu consequat ac felis donec. Id nibh tortor id aliquet lectus. Cum sociis natoque penatibus et magnis dis parturient montes.", img_url: "https://upload.wikimedia.org/wikipedia/commons/8/8e/East_69th_Street_001.JPG" )

User.create(name: "Anthony Soprano", username: "NJBoss2000", email: "email", img_url: "https://i1.wp.com/www.pissedoffgeek.com/wordpress/wp-content/uploads/2014/09/Tony-Soprano.jpg?fit=612%2C380")
Guide.create(user_id: 6, title: "Waste Management Do's and Don'ts", category: "Community", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac odio tempor orci dapibus ultrices in. Laoreet non curabitur gravida arcu ac tortor. Tortor id aliquet lectus proin nibh nisl condimentum id. Lobortis feugiat vivamus at augue eget. Pellentesque diam volutpat commodo sed. Morbi blandit cursus risus at. Molestie nunc non blandit massa enim. Magnis dis parturient montes nascetur ridiculus mus mauris. Viverra nibh cras pulvinar mattis nunc sed blandit. Sit amet commodo nulla facilisi nullam vehicula ipsum. Maecenas pharetra convallis posuere morbi leo urna molestie at. Et ligula ullamcorper malesuada proin libero nunc consequat. Semper auctor neque vitae tempus quam pellentesque nec. Sed felis eget velit aliquet sagittis id consectetur purus ut. Elit ullamcorper dignissim cras tincidunt. Semper eget duis at tellus at urna condimentum. Lectus nulla at volutpat diam ut.

    Ultrices dui sapien eget mi proin sed libero enim sed. Risus viverra adipiscing at in tellus integer feugiat. Facilisis sed odio morbi quis commodo odio aenean. Amet risus nullam eget felis eget nunc. Ut porttitor leo a diam sollicitudin tempor id eu. Lectus sit amet est placerat in egestas erat. Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Nisl rhoncus mattis rhoncus urna neque viverra. Sit amet porttitor eget dolor morbi non arcu risus. At in tellus integer feugiat scelerisque varius morbi enim nunc. Tincidunt lobortis feugiat vivamus at augue eget. Vivamus at augue eget arcu dictum varius duis. Maecenas pharetra convallis posuere morbi leo urna molestie. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Tortor id aliquet lectus proin nibh nisl condimentum id. Id aliquet risus feugiat in ante metus dictum at. Bibendum at varius vel pharetra vel turpis nunc eget. Justo laoreet sit amet cursus sit amet dictum sit. Enim ut tellus elementum sagittis vitae et leo duis ut. Rutrum tellus pellentesque eu tincidunt tortor.
    
    Eu consequat ac felis donec. Id nibh tortor id aliquet lectus. Cum sociis natoque penatibus et magnis dis parturient montes. Vulputate dignissim suspendisse in est ante in. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Volutpat est velit egestas dui id ornare arcu odio. Ullamcorper sit amet risus nullam eget felis eget nunc lobortis. Congue quisque egestas diam in arcu cursus euismod quis viverra. Enim ut tellus elementum sagittis vitae et. In hac habitasse platea dictumst quisque. Morbi tincidunt ornare massa eget. Nunc faucibus a pellentesque sit amet porttitor eget.", img_url: "https://miro.medium.com/max/2560/1*SOmFaCZ7q6M7NGyYmEK9pQ.jpeg" )

Token.create(user_id: 1)
Token.create(user_id: 1)
Token.create(user_id: 1)
Token.create(user_id: 1)
Token.create(user_id: 1)

Token.create(user_id: 2)
Token.create(user_id: 2)
Token.create(user_id: 2)
Token.create(user_id: 2)
Token.create(user_id: 2)

Token.create(user_id: 3)
Token.create(user_id: 3)
Token.create(user_id: 3)
Token.create(user_id: 3)
Token.create(user_id: 3)

Token.create(user_id: 4)
Token.create(user_id: 4)
Token.create(user_id: 4)
Token.create(user_id: 4)
Token.create(user_id: 4)

Token.create(user_id: 5)
Token.create(user_id: 5)
Token.create(user_id: 5)
Token.create(user_id: 5)
Token.create(user_id: 5)

Token.create(user_id: 6)
Token.create(user_id: 6)
Token.create(user_id: 6)
Token.create(user_id: 6)
Token.create(user_id: 6)

